package com.orderdetails.db.orderdetails_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ItemBase PLEASE EDIT ../Item.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Item object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.jdbc.core.RowMapper;
import com.orderdetails.db.orderdetails_db.entity.Item;

public class ItemBase implements RowMapper<Item>{
	
	private Long _id;
	
	// Attributes
    private String Description;
    private String Name;
    private Number Price;
	
	
	
	@Override
	public Item mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Item obj = new Item();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setDescription(rs.getString("Description"));
			obj.setName(rs.getString("Name"));
			obj.setPrice(rs.getBigDecimal("Price"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getDescription() {
		return Description;
	}


	public void setDescription(String Description) {
		this.Description = Description;
	}
	public String getName() {
		return Name;
	}


	public void setName(String Name) {
		this.Name = Name;
	}
	public Number getPrice() {
		return Price;
	}


	public void setPrice(Number Price) {
		this.Price = Price;
	}
	
    
    
    
    
}